package com.member.common.dto;

import java.util.List;

/**
 * 用于树结构显示的
 * https://www.jstree.com
 *
 * {
         id          : "string" // will be autogenerated if omitted
         text        : "string" // node text
         icon        : "string" // string for custom
         state       : {
         opened    : boolean  // is the node open
         disabled  : boolean  // is the node disabled
         selected  : boolean  // is the node selected
         },
         children    : []  // array of strings or objects
         li_attr     : {}  // attributes for the generated LI node
         a_attr      : {}  // attributes for the generated A node
 }
 */
public class JTreeDto<T> {

    private String text;
    private String icon;
    private List<JTreeDto<T>> children;
    private T data;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public List<JTreeDto<T>> getChildren() {
        return children;
    }

    public void setChildren(List<JTreeDto<T>> children) {
        this.children = children;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }
}
